name: Run on Browserstack

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @marquee'
        required: false
        type: string

jobs:
  platform_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: Running tests on Browserstack
    runs-on: ${{ matrix.os }}
    env:
      WORKFLOW_NAME: 'Commerce Debug Nala Run'

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Run Nala ${{ matrix.os }}
        run: bash runOnBrowserstack.sh milo ${{ inputs.tags }}
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Persist Output
        uses: actions/upload-artifact@v3
        if: failure()      
        with:
           name: playwright-output
           path: mili ## Folder used in playwright.config.js `outputDir`
           retention-days: 30
