name: Run Nala Manually

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags, if empty all tests will run. i.e., @marquee'
        required: false
        type: string
      platform:
        description: 'Platform to run tests on; select one, options: [ubuntu-latest, windows-latest, macos-latest]'
        required: true
        type: string

jobs:
  action:
    name: Running tests
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Nala ${{ inputs.platform }}
        uses: ./
        env:
          labels: ${{ inputs.tags }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
          HLX_TKN: ${{ secrets.HLX_TKN }}
          SLACK_WH: ${{ secrets.SLACK_WH }}          
      - name: Persist JSON Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nala-results
          path: nala-results.json
          retention-days: 30
      - name: Persist Output
        uses: actions/upload-artifact@v3
        if: failure()      
        with:
           name: playwright-output
           path: mili ## Folder used in playwright.config.js `outputDir`
           retention-days: 30
      - name: Run Nala ${{ matrix.os }}
        run: bash runOnBrowserstack.sh milo ${{ inputs.tags }}
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
